### PR TITLE
adding a parameter to list the fields to serialize

### PR DESCRIPTION
**Pull request by victorarias**

### CODE REVIEW

**Comment by danheberden** [comment]
Thanks for this pull request, it's a cool idea! However, i'm a bit leery of this feature, for a few reasons. 1) would the object passed be `$('whatever').serializeObject( { foo: true, baz: true, omg: true } )`? That seems a bit verbose and crazy. Also, the same thing could be done with underscore's `_.intersection()`. I feel like if we _did_ put this feature in, passing an array of fields would be better and then build the object manually. What do you think?

**Comment by danheberden** [comment]
Hmm, nevermind about the intersection() idea, as we're dealing with objects, heh

**Comment by victorarias** [comment]
I agree with you. Passing an object was a lame idea, so I already changed it to be an array. I've used $.inArray instead of creating the object manually, but I think that if you agree to accept the feature I can change this.

The team I'm working with came with this necessity because we use a lot of Backbone.js Views to the same model at the same time, and we got some issues with some upper level view re-serializing fields that some nested view already got, causing problems when the nested view need to change a value before setting to the model...

**Comment by danheberden** [comment]
`$.inArray` would be convenient, but slow compared to making the object once and just checking for `fields[name]` (basically building your original idea but starting with an array). If you want to try to make it happen with a minimal code size increase, I'd be interested in seeing it. Also, an aside - try to follow the code style (i, for the most part, follow this: http://docs.jquery.com/JQuery_Core_Style_Guidelines) so it matches :D

**Comment by victorarias** [comment]
Yes, using an object is much faster than a linear search. The  last commit
was only to see if I understood your idea. I'll code that tonight.

**Comment by victorarias** [comment]
And I'll also fix the code style! :D

**Comment by danheberden** [comment]
@victorarias Can you make sure this works with the latest master and add the feature to the README so I can merge it in?

**Pull request closed without merging**
